#actual postgres setup
default: &default
  adapter: postgresql
  encoding: utf8
  host: <%= ENV.fetch('DATABASE_HOST') %>
  username: <%= ENV.fetch('POSTGRES_USER') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>
  database: <%= ENV.fetch('POSTGRES_DB') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  variables:
    statement_timeout: 5000

development:
  <<: *default
  database: mkpeerage_development

test:
  <<: *default
  database: mkpeerage_test

production:
  <<: *default
  database: mkpeerage_production
