#actual postgres setup
default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: mkpeerage_development

test:
  <<: *default
  database: mkpeerage_test

production:
  <<: *default
  database: mkpeerage_production
