name: Run Tests

on: push

jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: mk-peerage
          POSTGRES_DB: mk-peerage_development
          POSTGRES_PASSWORD: mk-peerage
        ports: ["5432:5432"]

    steps:
      - uses: actions/checkout@v2
      - name: Create .env file
        run: |
          sed 's/DATABASE_HOST=database/DATABASE_HOST=localhost/' .env-dev-values > .env-actions
          cat .env-example .env-actions > .env
      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
      - name: Set up Ruby 3.1.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
          bundler-cache: true
      - name: Setup up node 12.22.12
        uses: actions/setup-node@v2
        with:
          node-version: '12.22.12'
          cache: 'yarn'
      - name: Install yarn packages
        run: |
          yarn policies set-version 1.22.18
          yarn install --frozen-lockfile
      - name: Set up DB
        run: bundle exec rails db:setup
      - name: Run tests
        run: bundle exec rspec
